---
name: Terraform
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
env:
  TERRAFORM_VERSION: 1.5.6
  KICS_resource_without_tag: 'e38a8e0a-b88b-4902-b3fe-b0fcb17d5c10'            # KICS Query 'Resource Not Using Tags' - provider default tags used instead
  KICS_alb_deletion_protection: 'afecd1f1-6378-4f7e-bb3b-60c35801fdd4'         # KICS Query 'ALB Deletion Protection Disabled'


jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff
        continue-on-error: true

      - uses: actions/github-script@v3
        if: ${{ failure() }}
        env:
          RESULT: "terraform\n${{ steps.fmt.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            <details><summary>Show Result</summary>

            \`\`\`${ process.env.RESULT }\`\`\`
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  kics-scan:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'repo'
      - name: KICS Github Action
        uses: checkmarx/kics-action@v1.7.0
        with:
          path: 'repo'
          exclude_paths: 'repo/examples'
          output_path: 'results'
          platform_type: terraform
          fail_on: high,medium
          exclude_queries: '${{ env.KICS_resource_without_tag }},${{ env.KICS_alb_deletion_protection }}'
          enable_comments: true
          enable_annotations: true
      - name: Display KICS Results
        run: |
          cat results/results.json
